name = "abi-lean"
version = "0.1.0"
defaultTargets = ["EvmAbi"]

[[lean_lib]]
name = "EvmAbi"

[[lean_exe]]
name = "abi-lean-test"
root = "EvmAbi.Test"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"
