name = "abi-lean"
version = "0.1.0"
defaultTargets = ["abi-lean"]

[[lean_lib]]
name = "EvmAbi"

[[lean_exe]]
name = "abi-lean"
root = "Main"

[[lean_exe]]
name = "abi-lean-test"
root = "EvmAbi.Test"
